version: '3.4'
services:
  db:
    image: postgres:14.10
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2025      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo18:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10018:8069"
      - "20018:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2025
    volumes:
      #- /etc/timezone:/etc/timezone:trt
      #- /etc/localtime:/etc/localtime:trt
      - ./entrypoint.sh:/entrypoint.sh   
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5051:80
    restart: always
    links:
      - db:db
    environment:
      PGADMIN_DEFAULT_EMAIL: 'email@to_be_modified'    
      PGADMIN_DEFAULT_PASSWORD: 'to_be_modified'
     # VIRTUAL_HOST: 
     # LETSENCRYPT_HOST:
     # VIRTUAL_PORT: 5051
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      #- /var/run/docker.sock:/tmp/docker.sock
